num_steps: 1000000
batch_size: 64
lr: 0.0005
memory_size: 25000
gamma: 0.99
multi_step: 1
target_entropy_ratio: 0.98
start_steps: 5000
update_interval: 4
target_update_interval: 1000
use_per: False
dueling_net: False
num_eval_steps: 10000
max_episode_steps: 300
log_interval: 10
eval_interval: 10000
